-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 09:31:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vystup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vystup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vystup` DEFAULT CHARACTER SET utf8 ;
USE `vystup` ;

-- -----------------------------------------------------
-- Table `vystup`.`horolezec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vystup`.`horolezec` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vystup`.`hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vystup`.`hora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `vyska` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vystup`.`vystup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vystup`.`vystup` (
  `horolezec_id` INT NOT NULL,
  `hora_id` INT NOT NULL,
  `datum` DATETIME NULL,
  PRIMARY KEY (`horolezec_id`, `hora_id`),
  INDEX `fk_horolezec_has_hora_hora1_idx` (`hora_id` ASC),
  INDEX `fk_horolezec_has_hora_horolezec_idx` (`horolezec_id` ASC),
  CONSTRAINT `fk_horolezec_has_hora_horolezec`
    FOREIGN KEY (`horolezec_id`)
    REFERENCES `vystup`.`horolezec` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horolezec_has_hora_hora1`
    FOREIGN KEY (`hora_id`)
    REFERENCES `vystup`.`hora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
