-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 13:14:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema evidence_stravy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evidence_stravy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `evidence_stravy` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `evidence_stravy` ;

-- -----------------------------------------------------
-- Table `evidence_stravy`.`stravnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_stravy`.`stravnik` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evidence_stravy`.`polevka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_stravy`.`polevka` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evidence_stravy`.`hlavni_chod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_stravy`.`hlavni_chod` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evidence_stravy`.`denni_nabidka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_stravy`.`denni_nabidka` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `datum` VARCHAR(45) NOT NULL,
  `polevka_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nabidka_polevka1_idx` (`polevka_id` ASC) VISIBLE,
  UNIQUE INDEX `datum_UNIQUE` (`datum` ASC) VISIBLE,
  CONSTRAINT `fk_nabidka_polevka1`
    FOREIGN KEY (`polevka_id`)
    REFERENCES `evidence_stravy`.`polevka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evidence_stravy`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_stravy`.`menu` (
  `hlavni_chod_id` INT UNSIGNED NOT NULL,
  `denni_nabidka_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`hlavni_chod_id`, `denni_nabidka_id`),
  INDEX `fk_hlavni_chod_has_denni_nabidka_denni_nabidka1_idx` (`denni_nabidka_id` ASC) VISIBLE,
  INDEX `fk_hlavni_chod_has_denni_nabidka_hlavni_chod1_idx` (`hlavni_chod_id` ASC) VISIBLE,
  CONSTRAINT `fk_hlavni_chod_has_denni_nabidka_hlavni_chod1`
    FOREIGN KEY (`hlavni_chod_id`)
    REFERENCES `evidence_stravy`.`hlavni_chod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hlavni_chod_has_denni_nabidka_denni_nabidka1`
    FOREIGN KEY (`denni_nabidka_id`)
    REFERENCES `evidence_stravy`.`denni_nabidka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evidence_stravy`.`objednavka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evidence_stravy`.`objednavka` (
  `stravnik_id` INT UNSIGNED NOT NULL,
  `menu_hlavni_chod_id` INT UNSIGNED NOT NULL,
  `menu_denni_nabidka_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`stravnik_id`, `menu_hlavni_chod_id`, `menu_denni_nabidka_id`),
  INDEX `fk_stravnik_has_menu_menu1_idx` (`menu_hlavni_chod_id` ASC, `menu_denni_nabidka_id` ASC) VISIBLE,
  INDEX `fk_stravnik_has_menu_stravnik1_idx` (`stravnik_id` ASC) VISIBLE,
  CONSTRAINT `fk_stravnik_has_menu_stravnik1`
    FOREIGN KEY (`stravnik_id`)
    REFERENCES `evidence_stravy`.`stravnik` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stravnik_has_menu_menu1`
    FOREIGN KEY (`menu_hlavni_chod_id` , `menu_denni_nabidka_id`)
    REFERENCES `evidence_stravy`.`menu` (`hlavni_chod_id` , `denni_nabidka_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
