-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 09:19:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kviz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kviz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kviz` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `kviz` ;

-- -----------------------------------------------------
-- Table `kviz`.`kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kviz`.`kategorie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kviz`.`otazky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kviz`.`otazky` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kategorie_id` INT UNSIGNED NOT NULL,
  `zneni` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_otazky_kategorie_idx` (`kategorie_id` ASC),
  UNIQUE INDEX `zneni_UNIQUE` (`zneni` ASC),
  CONSTRAINT `fk_otazky_kategorie`
    FOREIGN KEY (`kategorie_id`)
    REFERENCES `kviz`.`kategorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kviz`.`odpovedi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kviz`.`odpovedi` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `otazky_id` INT UNSIGNED NOT NULL,
  `zneni` VARCHAR(100) NOT NULL,
  `spravna` ENUM('NE', 'ANO') NOT NULL DEFAULT 'NE',
  PRIMARY KEY (`id`),
  INDEX `fk_odpovedi_otazky1_idx` (`otazky_id` ASC),
  CONSTRAINT `fk_odpovedi_otazky1`
    FOREIGN KEY (`otazky_id`)
    REFERENCES `kviz`.`otazky` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kviz`.`uzivatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kviz`.`uzivatele` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(45) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kviz`.`odpovedi_uzivatele_na_otazky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kviz`.`odpovedi_uzivatele_na_otazky` (
  `uzivatele_id` INT UNSIGNED NOT NULL,
  `odpovedi_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`uzivatele_id`, `odpovedi_id`),
  INDEX `fk_odpovedi_uzivatele_na_otazky_uzivatele1_idx` (`uzivatele_id` ASC),
  INDEX `fk_odpovedi_uzivatele_na_otazky_odpovedi1_idx` (`odpovedi_id` ASC),
  CONSTRAINT `fk_odpovedi_uzivatele_na_otazky_uzivatele1`
    FOREIGN KEY (`uzivatele_id`)
    REFERENCES `kviz`.`uzivatele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_odpovedi_uzivatele_na_otazky_odpovedi1`
    FOREIGN KEY (`odpovedi_id`)
    REFERENCES `kviz`.`odpovedi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
