-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 14:02:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema piva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema piva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `piva` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `piva` ;

-- -----------------------------------------------------
-- Table `piva`.`zeme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piva`.`zeme` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piva`.`mesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piva`.`mesto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `zeme_id` INT UNSIGNED NOT NULL,
  `GPS` POINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mesto_zeme_idx` (`zeme_id` ASC) VISIBLE,
  CONSTRAINT `fk_mesto_zeme`
    FOREIGN KEY (`zeme_id`)
    REFERENCES `piva`.`zeme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piva`.`pivovar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piva`.`pivovar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mesto_id` INT UNSIGNED NOT NULL,
  `nazev` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pivovar_mesto1_idx` (`mesto_id` ASC) VISIBLE,
  CONSTRAINT `fk_pivovar_mesto1`
    FOREIGN KEY (`mesto_id`)
    REFERENCES `piva`.`mesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piva`.`SRM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piva`.`SRM` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `low` INT UNSIGNED NOT NULL,
  `hi` INT UNSIGNED NULL,
  `barva` VARCHAR(45) NOT NULL,
  `popis` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `low_UNIQUE` (`low` ASC) VISIBLE,
  UNIQUE INDEX `hi_UNIQUE` (`hi` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `piva`.`pivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piva`.`pivo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pivovar_id` INT UNSIGNED NOT NULL,
  `nazev` VARCHAR(45) NOT NULL,
  `horkost` INT UNSIGNED NULL DEFAULT jednotka IBU,
  `hustota` INT UNSIGNED NULL DEFAULT 'stupeň, extrakt původní mladiny, Měří se ve stupnicích Plato (°P)',
  `ABV` FLOAT UNSIGNED NULL DEFAULT alkohol v procentech objemu,
  `SRM_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pivo_pivovar1_idx` (`pivovar_id` ASC) VISIBLE,
  INDEX `fk_pivo_SRM1_idx` (`SRM_id` ASC) VISIBLE,
  CONSTRAINT `fk_pivo_pivovar1`
    FOREIGN KEY (`pivovar_id`)
    REFERENCES `piva`.`pivovar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pivo_SRM1`
    FOREIGN KEY (`SRM_id`)
    REFERENCES `piva`.`SRM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
